import geopandas as gpd 
from paths import data_path

data_path = data_path + "/Vic/"
output_path = data_path + "cleaned_data/"

shape = f"{data_path}SDM746344/landuse_2016.shp"

gdf = gpd.read_file(shape)

gdf.loc[gdf['TENURE'] == "PUBLIC", "Ownership"] = "Public"
gdf.loc[gdf['TENURE'] == "PRIVATE", "Ownership"] = "Private"

pastoral = ['Mixed farming and grazing  (generally more than 20ha)', 'Livestock Production  Beef Cattle',
'Mixed farming and grazing', 'Livestock Production (Dairy Cattle)', 'Livestock Production (Sheep)', 'Piggery', 'Orchards, Groves and Plantations']

gdf.loc[gdf['LU_DESC'].isin(pastoral), 'Ownership'] = "Pastoral"


gdf.loc[gdf['TENURE'] == "PUBLIC", "Control"] = "Public"
gdf.loc[gdf['TENURE'] == "PRIVATE", "Control"] = "Private"
gdf.loc[gdf['LU_DESC'].isin(pastoral), 'Control'] = "Private"


gdf.to_file(f"{output_path}vic_pub_priv_past.shp")

# ['Unclassified Private Land' 'School Primary - Public/Private'
#  'Reserved Land' 'Mixed farming and grazing  (generally more than 20ha)'
#  'Separate House and Curtilage' 'Detached Home'
#  'Vacant Residential Rural / Rural Lifestyle (0.4 to 20ha)'
#  'Railway Line Land and Improvements in use' 'Parks and Gardens (Local)'
#  'Poultry (broiler production)' 'Vineyard'
#  'Electricity Substation / Terminal' 'Nature Reserve'
#  'Miscellaneous Building on Residential Rural Land (>1 and<20ha)'
#  'Vacant Englobo Residential Subdivisional Land'
#  'Reserved Roads / Unused Roads' 'Community Service Facilities or Other'
#  'Softwood Plantation' 'Water Treatment Plant'
#  'Vacant Residential Home Site / Surveyed Lot'
#  'Unspecified - Transport, Storage, Utilities and Communication'
#  'Telecommunication Towers and Aerials' 'State Forest'
#  'Fire Station Facility' 'Major Water Conduits'
#  'Main Highways (including national routes)'
#  'Church, Temple, Synagogue, etc' 'Conservation Area - Public'
#  'Water Storage Tanks, Pressure Control Towers and Pumping Stations'
#  'Livestock Production (Sheep)' 'Mixed Use Occupation'
#  'Bulk Grain Storage (structures)' 'Halls and Service Clubrooms'
#  'Native Hardwood (standing timber)'
#  'Pub/Tavern/Hotel/Licensed Club/Restaurant/Licensed Restaurant/Nightclub'
#  'General Purpose Warehouse'
#  'School / College Secondary / Technical School - Public'
#  'Other unspecified Extractive Industry' 'Abattoirs'
#  'General Purpose Factory' 'Telephone Exchange - Purpose Built'
#  'Natural Monument / Feature'
#  'Culture, recreation and sport (National/State/Regional)'
#  'Native Vegetation / Bushland Without Covenant / Agreement'
#  'Livestock Production (Beef Cattle)' 'Protected Seascape - Public'
#  'Tourist Park / Caravan Park / Camping Ground'
#  'Sewerage / Stormwater Pipelines'
#  'Outdoor Sports Grounds - town or suburban facilities'
#  'Miscellaneous Buildings on Residential Land'
#  'Operating mine unspecified'
#  'Retail Premises (single occupancy/single title/single stratum)'
#  'Water Catchment Area' 'Livestock Production (Dairy Cattle)'
#  'Forestry (Commercial Timber Production)' 'Retail Premises'
#  'Residential Hotel / Motel / Apartment Hotel Complex'
#  'General Cropping (generally more than 20ha plantings)'
#  'Residential Development Site' 'Community / Neighbourhood Facility'
#  'Short Term Holiday Accommodation' 'Orchards, Groves and Plantations'
#  'Market Garden - Vegetables (generally less than 20ha plantings)'
#  'Gravel / Stone (Quarry)' 'Horse Stud / Training Facilities / Stables'
#  'Domestic Livestock Grazing' 'Outdoor Sports Grounds / Complex'
#  'Industrial Development Site'
#  'Cable Lines, Conduits and Special Purpose Below St'
#  'National Park - Land' 'Sewerage / Stormwater Pump Stations'
#  'Fuel Outlet / Garage / Service Station' 'Sawmill'
#  'Manufacturing Materials (Quarry)'
#  'Water Storage Dam / Reservoir (Non-Catchment)'
#  'Sewerage / Stormwater Treatment Plant Site' 'Piggery'
#  'Stock sales yards' 'Forest Reserves - Public' 'Water Supply'
#  'Vacant Religious Purposes Development Site'
#  'Outdoor Sports - Extended Areas / Cross Country'
#  'Electricity Distribution / Reticulation Lines'
#  'Indoor Sports Centre etc.' 'Bed and Breakfast' 'Airstrip'
#  'Vacant Industrial Englobo Land' 'Cabin / Accommodation'
#  'Suburban and Rural Roads' 'Water Storage Dam/Reservoir (Non-Catchment)'
#  'Mixed farming and grazing  (generally more than 20 ha)'
#  'Residential Rural / Rural Lifestyle (0.4 to 20 Hectares)'
#  'Transport (Marine)' 'Livestock Production  Beef Cattle'
#  'Retail Premises (multiple occupancies, usually single title or the parent title for stratum units)'
#  'Water - Urban Distribution Network (through easements, freehold and public land)'
#  'Sewerage / Stormwater Pipelines (through easements, freehold and public land)'
#  'Market Garden  Vegetables (generally less than 20ha plantings)'
#  'Horse Stud / Training Facilities/Stables'
#  'Vacant Residential Rural / Rural Lifestyle (0.4 to 20 Hectares)'
#  'Poultry (egg production)' 'Livestock Production  Sheep' 'Freeways'
#  'Commercial Development Site' 'Protected Landscape - Public'
#  'Aged Care Complex / Special Accommodation / Nursing Home'
#  'Water - Urban Distribution Network' 'Water Catchment Dam / Reservoir'
#  'Railway / Tramway Line Closed / Unused'
#  'Racecourse / Tracks / Showground' 'Specialised Cropping' 'Post Offices'
#  'Coolstore / Coldstore' 'Vacant Land'
#  'Residential Hotel/Motel / Apartment Hotel Complex'
#  'Miscellaneous Building on Residential Rural Land (0.4 to 20 Hectares)'
#  'Plant / Tree Nursery'
#  'Industrial Land (with buildings which add no value)'
#  'Food Processing Factory' 'Member Club Facility'
#  'Single Unit/Villa Unit/Townhouse' 'Conjoined Strata Unit / Townhouse'
#  'Native Vegetation / Bushland Without Covenant/Agreement'
#  'Vacant Residential Home Site/Surveyed Lot'
#  'Residential Investment Flats' 'Parks and Gardens'
#  'Fuel Outlet/Garage/Service Station'
#  'Residential Land (with buildings which add no value)'
#  'Water Storage Tanks, Pressure Control Towers and Pumping Stations.'
#  'Major Industrial Complex  Special Purpose Improvements'
#  'School Primary  Public/Private'
#  'Glasshouse Plant / Vegetable Production' 'Public Conveniences'
#  'Kennel / Cattery' 'Equestrian Centre' 'Sanitary Land Fill'
#  'Piers, Storages, and Slipways'
#  'Single Strata Unit / Villa Unit / Townhouse'
#  'Culture, recreation and sport' 'Quarry (in use): Gravel/Stone'
#  'State Park' 'Major Industrial Complex' 'Technical and Further Education'
#  'Commercial Land (with buildings which add no value)'
#  'Indoor Sports Grounds / Complex' 'Regional Park'
#  'Vacant Government Administration Development Site'
#  'Serviced Apartments / Holiday Units'
#  'Airfield (includes associated open space)' 'Community Health Centre'
#  'Bus Maintenance Depot' 'Research Institute - Public' 'Rendering Plant'
#  'Religious Study Centre'
#  'Native Vegetation / Bushland With Covenant / Agreemement' 'Wetlands'
#  'Gravel / Stone site (not in use)' 'Sand (Quarry)' 'Open Area Storage'
#  'Religious Hall' 'Early Childhood Development Centre - Kindergarten'
#  'Hardwood Plantation' 'Conservation Area - Private' 'Office Premises'
#  'Government Administration' 'Secondary Roads'
#  'Quarry / Mine (open cut) Exhausted (dry)' 'Vacant Site - Sporting Use'
#  'Civic Buildings' 'Gas Distribution / Reticulation Pipelines'
#  'Protected Landscape / Seascape' 'Retirement Village Complex'
#  'Health Clinic' 'Shack / Hut / Donga' 'Multi-Purpose Fuel Outlet'
#  'Market Garden  Vegetables' 'Man-made Evaporation Basin'
#  'Cattle Feed Lot' 'Sand site (not in use)' 'Vehicle Sales Centre'
#  'Motor Racing Tracks / Speedways' 'Defence Services/Military Base'
#  'Wilderness Area' 'Manufacturing Materials (not in use)'
#  'Metals (other than gold open cut)' 'Gold (open cut)'
#  'Residential Hotel / Motel / Apartment Hotel Units'
#  'Regional / District / Neighbourhood Shopping Complex'
#  'Rural and Community Camps' 'Extractive less than 2 Metres (unspecified)'
#  'Commercial Flwer and Plant Growing - (outdoor)' 'Disability Housing'
#  'Refuse Transfer Station' 'National Company Retail'
#  'Aquaculture Breeding / Research  Facilities /  Fish Hatchery'
#  'Special Needs School'
#  'Guest Lodge / Back Packers / Bunkhouse / Youth Hostel'
#  'Water Sports - Swimming Pools / Aquatic Centres'
#  'Cultural Heritage Centre (Local)' 'Emergency Services Complex'
#  'Electricity Power Generators - Fuel Powered' 'Gas Transmission Pipeline'
#  'Rectory, Mance, Presbytery' 'National Company Restaurant'
#  'Public Hospital' 'National Park - Marine' 'Infant Welfare Centre'
#  'Non-Native Animals' 'Airport Hangar Building'
#  'Bus Interchange Centre / Bus Terminal' 'Granny Flat / Studio'
#  'Cable Lines, Conduits and Special Purpose Below Street Level Communication Line Tunnels  not being sewers (through easements, freehold and public la*'
#  'Individual Car Park Site' 'Airport Terminal Building - Passengers'
#  'Semi-Detached / Terrace Home / Row House' 'Ground Level Parking'
#  'Vacant Site - Cultural Use' 'Vacant Land mining unspecified'
#  'Soil  (Quarry)' 'Hazardous Materials / Toxic Storage Centre'
#  'Tannery / Skins Depot & Drying' 'Monument / Memorial (Local)'
#  'Ancillary structures (not capable of occupation)'
#  'Library / Archives (National/State/Regional)' 'Retirement Village Unit'
#  'Non metals (other than Uranium open cut)'
#  'Bulk Grain Storage (earthen walls and flooring - pit bunker)'
#  'Local Government' 'University - Private / Public'
#  'Boarding House / Private Hotel / Dormitory Accommodation'
#  'Amusement Parks etc' 'Water Sports - Open Areas'
#  'Residential College / Quarters' 'Individual Flat'
#  'Aged Care Amenities Buildings' 'House and Flat / Studio'
#  'Bulk Liquid Storage Fuel Depot / Tank Farm'
#  'Television / Radio Station - Purpose Built'
#  'Tourism Infrastructure (Local Attractions)'
#  'Black or Brown Coal (open cut)' 'Railway Passenger Terminal Facilities'
#  'Motor Race Tracks / Speedways'
#  'Railway Passenger Terminal Facilities (including stations etc)'
#  'Metals (other than gold deep shaft)' 'Closed Roads'
#  'Creek Reserve(salt water)' 'Marinas and Yacht Clubs' 'Veterinary Clinic'
#  'Vacant Site  Sporting Use' 'Bike Track/Walking Trails'
#  'Extractive industry site with permit or reserve not in use: Sand'
#  'Forest Reserves - Private' 'Bike Track / Walking Trails'
#  'Commercial Flower and Plant Growing  (outdoor)' 'Gold (deep shaft)'
#  'Monument / Memorial (National/state regional)'
#  'Ski Fields (some commercial application)'
#  'Lighthouse and Navigation Aids' 'Kiosk' 'Cemetery'
#  'Boat Sheds, Bathing Boxes, Ramps and Jetties'
#  'Tramway Maintenance / Terminal Storage' 'Day Care Centre for Children'
#  'Water Sports  Open Areas' 'Health Surgery'
#  'Museum / Art Gallery (National/State/Regional)'
#  'Crematorium / Funeral Services'
#  'Racecourse/Tracks/Showground (sport involving animals, likely some commercial application)'
#  'Tourism Infrastructure  Local Attractions' 'Refuse Recycling'
#  'Wind Farm Electricity Generation' 'Petro Chemical Manufacturing'
#  'Electricity Transmission Lines'
#  'Early Childhood Development Centre  Kindergarten'
#  'Telecommunication Buildings / Maintenance Depots'
#  'Vacant Englobo Commercial Land' 'Yabby Farming' 'Strata unit or flat'
#  'Army Barracks/Administration Base'
#  'Vacant Education and Research Development Site'
#  'Museum / Art Gallery (Local)'
#  'Outdoor Sports  Extended Areas/Cross Country' 'Market Stall'
#  'Vacant Community Services Development Sites' 'Low Rise Office Building'
#  'Film / Movie Theatre, Playhouse / Traditional Theatre' 'Reserved land'
#  'Gas Production / Refinery'
#  'Vacant In globo Residential Subdivisional Land' 'Monument/Memorial'
#  'Centre for the Mentally Ill' 'Car Wash' 'Mixed farming and grazing'
#  'Sewerage/Stormwater Pipelines (through easements, freehold and public land)'
#  'Hydro Electricity Production' 'Protected Landscape - Private'
#  'Community Protection and Services Training Facility'
#  'Outdoor Sports  Extended Areas/Cross Country (likely some commercial application)'
#  'Reserved Roads/Unused Roads'
#  'School/College Secondary/Technical School  Public/Private'
#  'Oil Refinery' 'Special Purpose (Office)'
#  'Cultural Heritage Centre (National/State/Regional)' 'Gas Storage'
#  'Drive Ins' 'Creek Reserve (fresh water)' 'Coolstore/Coldstore'
#  'Water Catchment Dam/Reservoir' 'Police Facility'
#  'General Cropping (generally more than 20 ha plantings)'
#  'Wildlife Zoo / Park / Aquarium (Local)' 'Museum/Art Gallery'
#  'Ambulance Station Facility' 'Weighbridge' 'Private Hospital'
#  'Aged Care Complex/Special Accommodation/Nursing Home'
#  'Office Premises (single occupancy/single title/single stratum)'
#  'Telephone Exchange  Purpose Built' 'Casino' 'Hotel-Gaming'
#  'Residential Company Share Unit'
#  'Extractive industry site with permit or reserve not in use: Gravel/Stone'
#  'National Park  Land\r\n' 'Fish Farming - Sea Water Based'
#  'Community/Neighbourhood Facility' 'Club / Gaming / stand alone'
#  'Native Vegetation / Bushland With Covenant/Agreement'
#  'Fresh Water Lake Reserve' 'Multi-Level Office Building'
#  'Individual Car Park' 'Railway Freight Terminal Facilities'
#  'Industrial Development Airspace' 'Army Barracks / Administration Base'
#  'Guest Lodge/Back Packers/Bunkhouse/Youth Hostel'
#  'Bottle Shop / Licensed Liquor Outlet' 'Poultry - Open Range'
#  'Naval Specialised Facilities  Ground Based'
#  'Botanical Gardens (National/State/Regional)' 'Water (irrigation)'
#  'Water (stock and domestic)' 'Disused Well / Bore' 'Port Dock / Berth'
#  'Major Sports Facility (full commercial application)'
#  'Unspecified - Public, Education and Health Improved'
#  'Port Wharf / Pier and Apron' 'URBAN VOID' 'VOID'
#  'Library / Archives (Local)']

    